project:
  type: website
  output-dir: docs

website:
  title: FINAL PROJECT
  navbar:
    left:
      - href: index.qmd
        text: Report
      - data.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
