setup: |
  echo "Done installing project dependencies!"
---

# Reminder for ^^^:
# All commands executed in the setup block are done in a
# one-by-one fashion from the current working directory. This means
# that there is no history associated with running the commands and
# thus multiple commands must be run in a single chain.

# perform checks on a file

- final_project.ipynb:
    - description: Ensure that the final_project.ipynb file exists
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers in final_project.ipynb
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true

- data/final_project_data.csv:
    - description: Ensure that the final_project_data.csv file exists in the data directory
      check: ConfirmFileExists